export function getAllPostsQuery(){
    return{
        query:
        `query{
            getAllPosts{
                _id
                title
                description
                creator{
                    _id
                    username
                }
                latitude
                longitude
                emoji
                date
                isNightmode
            }
        }`
    }
}

export function getAllCommentsByPostIdQuery(postId){
    return{
        query:
        `query{
            getAllCommentsByPostId(postId: "${postId}"){
                _id
                description
                creator{
                    _id
                    username
                }
                latitude
                longitude
                date
                post{
                    _id
                }
                childComments{
                    _id
                    description
                    creator{
                        _id
                        username
                    }
                    latitude
                    longitude
                    date
                    post{
                        _id
                    }
                    childComments{
                        _id
                        description
                        creator{
                            _id
                            username
                        }
                        latitude
                        longitude
                        date
                        post{
                            _id
                        }
                        childComments{
                            _id
                        }
                    }
                }
            }
        }`
    }
}

export function createPostQuery(title, description, creator, latitude, longitude, emoji){
    console.log(title);
    console.log(description);
    console.log(creator);
    console.log(latitude);
    console.log(longitude);
    return{
        query:
        `mutation{
            createPost(title: "${title}", description:"${description}", creator: "${creator}", latitude: ${latitude}, longitude: ${longitude}, emoji: "${emoji}"){
                _id
                title
                description
                creator{
                    _id
                }
                latitude
                longitude
                date
            }
        }`
    }
}